[package]
name = "img"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
wasm-bindgen = "0.2"

[lib]
path = "src/main.rs"
crate-type = ["cdylib"]

[dev-dependencies]
wasm-bindgen-test = "0.3"